name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
      - uses: ./
      - run: |
          if [[ $(shorebird --version) =~ "Shorebird Engine • revision" ]]; then          
            echo '✅ Shorebird CLI is installed!'
          else
            echo '❌ Shorebird CLI is not installed.'
            exit 1
          fi
